# Generated by Django 5.0.6 on 2024-07-22 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogsettings",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                help_text="Website banner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="banner_color",
            field=models.CharField(
                default="#0", help_text="Background color of the banner.", max_length=9
            ),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="title_color",
            field=models.CharField(
                default="#FFFFFF", help_text="Color of the site title.", max_length=9
            ),
        ),
    ]
