# Generated by Django 5.1 on 2024-08-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_blogsettings_banner_blogsettings_banner_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogsettings",
            name="banner_color",
            field=models.CharField(
                default="#000000",
                help_text="Background color of the banner.",
                max_length=9,
            ),
        ),
    ]
