name: Python Tests
run-name: python-test
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  ruff:
    container: python:3.13-slim-bookworm
    if: ${{ github.event_name == 'pull_request' }}
    name: 'Python linter: ruff'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/actions/build
    - id: file-changed
      name: File changed
      uses: tj-actions/changed-files@v45
      with:
        files_yaml: |-
          python:
            - '**/*.py'
            - '!**/migrations/*.py'
    - id: run-ruff
      if: ${{ steps.file-changed.outputs.any_changed == 'true' }}
      name: Run ruff
      run: poetry run python-ruff ${{ steps.file-changed.outputs.all_changed_files
        }}
    - id: ruff-format
      if: ${{ steps.file-changed.outputs.any_changed == 'true' }}
      name: Ruff Format
      run: poetry run python-format ${{ steps.file-changed.outputs.all_changed_files
        }}
  lock:
    container: python:3.13-slim-bookworm
    if: ${{ github.event_name == 'pull_request' }}
    name: 'Python linter: poetry lock check'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/actions/build
    - id: run-lock
      name: Run poetry lock check
      run: poetry check --strict --lock
  mypy:
    container: python:3.13-slim-bookworm
    env:
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: '5432'
      DATABASE_USER: postgres
    if: ${{ github.event_name == 'pull_request' }}
    name: 'Python linter: mypy'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/actions/build
    - id: file-changed
      name: File changed
      uses: tj-actions/changed-files@v45
      with:
        files_yaml: |-
          python:
            - '**/*.py'
            - '!**/migrations/*.py'
    - id: run-mypy
      name: Run mypy
      run: poetry run python-type-check ${{ steps.file-changed.outputs.all_changed_files
        }}
  blog_site_tests:
    container: python:3.13-slim-bookworm
    env:
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: '5432'
      DATABASE_USER: postgres
    name: 'Python test: blog_site_tests'
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:16
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432/tcp
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/actions/build
    - id: run-blog-site-tests
      name: Run blog_site_tests
      run: poetry run python-test-suite blog_site_tests
  all_apps_tests:
    container: python:3.13-slim-bookworm
    env:
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: '5432'
      DATABASE_USER: postgres
    name: 'Python test: all_apps_tests'
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:16
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432/tcp
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/actions/build
    - id: run-all-apps-tests
      name: Run all_apps_tests
      run: poetry run python-test-suite all_apps_tests
  unit_tests:
    container: python:3.13-slim-bookworm
    env:
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: '5432'
      DATABASE_USER: postgres
    name: 'Python test: unit_tests'
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:16
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432/tcp
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/actions/build
    - id: run-unit-tests
      name: Run unit_tests
      run: poetry run python-test-suite unit_tests
  shell_tests:
    container: python:3.13-slim-bookworm
    env:
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: '5432'
      DATABASE_USER: postgres
    name: 'Python test: shell_tests'
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:16
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432/tcp
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/actions/build
    - id: run-shell-tests
      name: Run shell_tests
      run: poetry run python-test-suite shell_tests
  coverage:
    container: python:3.13-slim-bookworm
    env:
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: '5432'
      DATABASE_USER: postgres
      DEBUG: 1
    name: 'Python test: coverage'
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:16
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432/tcp
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/actions/build
    - id: install-system-dependencies
      name: Install system dependencies
      run: apt-get update && apt-get install -y gpg
    - id: run-coverage
      name: Run coverage
      run: 'poetry run python-coverage '
    - id: upload-coverage
      name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: 'true'
        files: coverage/report.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: 'true'
  python-tests-passed:
    container: python:3.13-slim-bookworm
    env:
      RESULTS: |-
        ${{ needs.ruff.result }}
        ${{ needs.lock.result }}
        ${{ needs.mypy.result }}
        ${{ needs.blog_site_tests.result }}
        ${{ needs.all_apps_tests.result }}
        ${{ needs.unit_tests.result }}
        ${{ needs.shell_tests.result }}
    if: ${{ always() }}
    name: 'Python test: OK'
    needs:
    - ruff
    - lock
    - mypy
    - blog_site_tests
    - all_apps_tests
    - unit_tests
    - shell_tests
    runs-on: ubuntu-latest
    steps:
    - id: test-results
      name: Test results
      run: |-
        echo $RESULTS
        for r in $RESULTS
        do
            if [ $r = "success" ] || [ $r = "skipped" ];
            then
                true
            else
                echo "Some tests failed"
                exit 1
            fi
        done
        echo "All tests passed"
